bot:
  token: "7656241581:AAHo0Dt2RWKw93uYQNV4riWBaDRgfGR8ayw"  # Токен вашего Telegram-бота
  admin_id: 123456789              # ID администратора для уведомлений

database:
  driver: "sqlite"                # Драйвер базы данных (sqlite3, postgres, mysql)
  dsn: "vpn-bot.db"                # DSN для подключения (для SQLite — имя файла)

marzban:
  api_url: "http://81.31.244.167:8000"  # URL вашего Marzban-сервера
  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImFjY2VzcyI6InN1ZG8iLCJleHAiOjE3MzIxMzEyMzl9.HbIIttgs-fgu3n4nsC4NOU6kHdZMj-JpSBTFxmO-7Mk"            # API-ключ для работы с Marzban

payments:
  webhook_secret: "YOUR_WEBHOOK_SECRET"      # Секрет для валидации платежных webhook
  provider: "yookassa"                       # Провайдер платежей (например, yookassa, stripe)
  provider_config:
    yookassa:
      shop_id: "YOUR_SHOP_ID"
      secret_key: "YOUR_SECRET_KEY"

app:
  test_period_days: 7                        # Длительность тестового периода в днях
  default_traffic_limit_gb: 10               # Ограничение трафика по умолчанию в GB
  check_interval_minutes: 60                 # Интервал проверки баланса в минутах
