app:
    check_interval_minutes: 60
    default_traffic_limit_gb: 10
    test_period_days: 7
bot:
    admin_id: 123456789
    token: 7656241581:AAHo0Dt2RWKw93uYQNV4riWBaDRgfGR8ayw
database:
    driver: sqlite
    dsn: vpn-bot.db
marzban:
    api_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImFjY2VzcyI6InN1ZG8iLCJpYXQiOjE3MzM0NzMxMTEsImV4cCI6MTczMzU1OTUxMX0.JJ3mXcQlJX8eauI-ZLn48JukAw7qa-ULewwuxoRHP0E
    api_url: https://90.156.228.124:63055
    password: SS1XcMqa6Y
    username: admin
payments:
    provider: yookassa
    provider_config:
        yookassa:
            secret_key: YOUR_SECRET_KEY
            shop_id: YOUR_SHOP_ID
    webhook_secret: YOUR_WEBHOOK_SECRET
