app:
    check_interval_minutes: 60
    default_traffic_limit_gb: 10
    test_period_days: 7
bot:
    admin_id: 123456789
    token: 7656241581:AAHo0Dt2RWKw93uYQNV4riWBaDRgfGR8ayw
database:
    driver: sqlite
    dsn: vpn-bot.db
marzban:
    api_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImFjY2VzcyI6InN1ZG8iLCJleHAiOjE3MzIzNzI1MzF9.1kEPaDW6PccoZnnxuRSq-jy7193Qpfap7qjh1c7u7kQ
    api_url: http://81.31.244.167:8000
    password: XvGVzoEIiLMUkOK6
    username: admin
payments:
    provider: yookassa
    provider_config:
        yookassa:
            secret_key: YOUR_SECRET_KEY
            shop_id: YOUR_SHOP_ID
    webhook_secret: YOUR_WEBHOOK_SECRET
