app:
    check_interval_minutes: 60
    default_traffic_limit_gb: 10
    test_period_days: 8
bot:
    admin_id: 123456789
    token: 7656241581:AAHo0Dt2RWKw93uYQNV4riWBaDRgfGR8ayw
database:
    driver: sqlite
    dsn: vpn-bot.db
marzban:
    api_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImFjY2VzcyI6InN1ZG8iLCJpYXQiOjE3MzMxNDY4MTgsImV4cCI6MTczMzIzMzIxOH0.JbfG5M6kPII6Kegv8oNF-c1v8W9VGxomKHM799ASHnI
    api_url: https://90.156.228.124:63055
    password: SS1XcMqa6Y
    username: admin
payments:
    provider: yookassa
    provider_config:
        yookassa:
            secret_key: YOUR_SECRET_KEY
            shop_id: YOUR_SHOP_ID
    webhook_secret: YOUR_WEBHOOK_SECRET
